apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-products.fullname" . }}-secrets
  labels:
    {{- include "ecommerce-products.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-uri: {{ printf "mongodb://admin:admin123@%s:%d/%s?authSource=admin" .Values.mongodb.host (.Values.mongodb.port | int) .Values.mongodb.database | b64enc }}
